import type { ConcertMapInput } from "@/lib/concert-map-metrics";

const base = "demo-user";
const now = new Date().toISOString();

function demoConcert(
  data: Omit<ConcertMapInput, "user_id" | "created_at" | "notes">,
): ConcertMapInput {
  return {
    ...data,
    user_id: base,
    created_at: now,
    notes: null,
  };
}

/**
 * Demo concerts for dashboard preview (map, stats, charts) when the user has none logged.
 */
export const DASHBOARD_DEMO_CONCERTS: ConcertMapInput[] = [
  demoConcert({
    id: "demo-1",
    concert_name: "Summer Nights Tour",
    artist: "The Midnight Echo",
    venue: "Red Rocks Amphitheatre",
    city: "Morrison",
    state: "CO",
    concert_date: "2025-06-14",
    distance_from_home: 24,
    hours_at_event: 4,
    ticket_cost: 85,
    ticket_fees: 18,
    parking_cost: 25,
    food_drink_cost: 32,
    merchandise_cost: 40,
    lodging_cost: 0,
    travel_cost: 15,
    other_cost: 0,
    fun_rating: 9,
    latitude: 39.665538,
    longitude: -105.205749,
  }),
  demoConcert({
    id: "demo-2",
    concert_name: "Live at the Garden",
    artist: "Ava Stone",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    concert_date: "2025-03-22",
    distance_from_home: 1620,
    hours_at_event: 3.5,
    ticket_cost: 120,
    ticket_fees: 22,
    parking_cost: 0,
    food_drink_cost: 28,
    merchandise_cost: 55,
    lodging_cost: 189,
    travel_cost: 210,
    other_cost: 15,
    fun_rating: 10,
    latitude: 40.7505,
    longitude: -73.9934,
  }),
  demoConcert({
    id: "demo-3",
    concert_name: "Coastline at Red Rocks",
    artist: "Coastline",
    venue: "Red Rocks Amphitheatre",
    city: "Morrison",
    state: "CO",
    concert_date: "2024-08-01",
    distance_from_home: 24,
    hours_at_event: 4,
    ticket_cost: 75,
    ticket_fees: 12,
    parking_cost: 20,
    food_drink_cost: 24,
    merchandise_cost: 0,
    lodging_cost: 0,
    travel_cost: 10,
    other_cost: 0,
    fun_rating: 8,
    latitude: 39.665538,
    longitude: -105.205749,
  }),
  demoConcert({
    id: "demo-4",
    concert_name: "Austin City Limits",
    artist: "River & Rail",
    venue: "Zilker Park",
    city: "Austin",
    state: "TX",
    concert_date: "2024-10-12",
    distance_from_home: 920,
    hours_at_event: 8,
    ticket_cost: 199,
    ticket_fees: 35,
    parking_cost: 0,
    food_drink_cost: 65,
    merchandise_cost: 30,
    lodging_cost: 145,
    travel_cost: 180,
    other_cost: 0,
    fun_rating: 9,
    latitude: 30.2648,
    longitude: -97.7469,
  }),
  demoConcert({
    id: "demo-5",
    concert_name: "Nashville Nights",
    artist: "Harbor Lights",
    venue: "Bridgestone Arena",
    city: "Nashville",
    state: "TN",
    concert_date: "2025-01-18",
    distance_from_home: 1150,
    hours_at_event: 3,
    ticket_cost: 95,
    ticket_fees: 16,
    parking_cost: 30,
    food_drink_cost: 22,
    merchandise_cost: 25,
    lodging_cost: 0,
    travel_cost: 95,
    other_cost: 0,
    fun_rating: 7,
    latitude: 36.1592,
    longitude: -86.7785,
  }),
  demoConcert({
    id: "demo-6",
    concert_name: "Windy City Fest",
    artist: "North Avenue",
    venue: "United Center",
    city: "Chicago",
    state: "IL",
    concert_date: "2024-05-05",
    distance_from_home: 980,
    hours_at_event: 3.5,
    ticket_cost: 110,
    ticket_fees: 20,
    parking_cost: 35,
    food_drink_cost: 30,
    merchandise_cost: 0,
    lodging_cost: 120,
    travel_cost: 140,
    other_cost: 0,
    fun_rating: 8,
    latitude: 41.8807,
    longitude: -87.6742,
  }),
  demoConcert({
    id: "demo-7",
    concert_name: "SoCal Stadium Tour",
    artist: "Neon Harbor",
    venue: "SoFi Stadium",
    city: "Los Angeles",
    state: "CA",
    concert_date: "2024-11-20",
    distance_from_home: 1020,
    hours_at_event: 4,
    ticket_cost: 145,
    ticket_fees: 28,
    parking_cost: 45,
    food_drink_cost: 38,
    merchandise_cost: 60,
    lodging_cost: 210,
    travel_cost: 175,
    other_cost: 0,
    fun_rating: 9,
    latitude: 33.9535,
    longitude: -118.3392,
  }),
  demoConcert({
    id: "demo-8",
    concert_name: "Pacific Sound",
    artist: "Rain City Collective",
    venue: "Climate Pledge Arena",
    city: "Seattle",
    state: "WA",
    concert_date: "2025-02-08",
    distance_from_home: 1320,
    hours_at_event: 3.5,
    ticket_cost: 98,
    ticket_fees: 18,
    parking_cost: 32,
    food_drink_cost: 26,
    merchandise_cost: 35,
    lodging_cost: 165,
    travel_cost: 220,
    other_cost: 0,
    fun_rating: 8,
    latitude: 47.6221,
    longitude: -122.354,
  }),
  demoConcert({
    id: "demo-9",
    concert_name: "O2 Arena Live",
    artist: "Glass Harbour",
    venue: "The O2",
    city: "London",
    state: "UK",
    concert_date: "2023-09-14",
    distance_from_home: 4700,
    hours_at_event: 3,
    ticket_cost: 88,
    ticket_fees: 14,
    parking_cost: 0,
    food_drink_cost: 42,
    merchandise_cost: 30,
    lodging_cost: 320,
    travel_cost: 890,
    other_cost: 25,
    fun_rating: 10,
    latitude: 51.503,
    longitude: 0.0032,
  }),
  demoConcert({
    id: "demo-10",
    concert_name: "Seine Summer Sessions",
    artist: "Lumière",
    venue: "Accor Arena",
    city: "Paris",
    state: "France",
    concert_date: "2023-07-02",
    distance_from_home: 5200,
    hours_at_event: 3.5,
    ticket_cost: 92,
    ticket_fees: 16,
    parking_cost: 0,
    food_drink_cost: 48,
    merchandise_cost: 22,
    lodging_cost: 280,
    travel_cost: 910,
    other_cost: 0,
    fun_rating: 9,
    latitude: 48.8387,
    longitude: 2.3785,
  }),
  demoConcert({
    id: "demo-11",
    concert_name: "Harbour Lights Toronto",
    artist: "Northern Tide",
    venue: "Scotiabank Arena",
    city: "Toronto",
    state: "Canada",
    concert_date: "2024-04-18",
    distance_from_home: 1750,
    hours_at_event: 3,
    ticket_cost: 105,
    ticket_fees: 19,
    parking_cost: 28,
    food_drink_cost: 34,
    merchandise_cost: 40,
    lodging_cost: 150,
    travel_cost: 260,
    other_cost: 0,
    fun_rating: 8,
    latitude: 43.6435,
    longitude: -79.3791,
  }),
  demoConcert({
    id: "demo-12",
    concert_name: "Miami Beach Fest",
    artist: "Coral Wave",
    venue: "Kaseya Center",
    city: "Miami",
    state: "FL",
    concert_date: "2025-04-05",
    distance_from_home: 1750,
    hours_at_event: 4,
    ticket_cost: 130,
    ticket_fees: 24,
    parking_cost: 40,
    food_drink_cost: 55,
    merchandise_cost: 45,
    lodging_cost: 195,
    travel_cost: 310,
    other_cost: 0,
    fun_rating: 9,
    latitude: 25.7814,
    longitude: -80.187,
  }),
];
